server:
  port: 8085
spring:
  application:
    name: API-GATEWAY-SERVICE
  cloud:
    gateway:
      routes:
        - id: GUEST-SERVICE
          uri: http://localhost:9091
          predicates:
            - Path=/hms/v1/**
             
        - id: STAFF-SERVICE
          uri: http://localhost:9093
          predicates:
            - Path=/hms/v2/**
        - id: PAYMENT-SERVICE
          uri: http://localhost:9092
         
          predicates:
            - Path=/hms/v3/**
        - id: RESERVATION-SERVICE
          uri: http://localhost:9094
          predicates:
            - Path=/hms/v4/**
        - id: LOGIN-SERVICE
          uri: http://localhost:8199
          predicates:
            - Path=/api/auth/**
    
            
           
        
        
    
            